### ISSUE TITLE
where is "libNUSurveyor.a"

### ISSUE THREAD

**Issue by Sophrinix** [NUARIG/nu_surveyor#82]
the instructions make sense up until this point. After which, I have no clue where libNUSurveyor.a is suppose to be

**Comment by yoon** [comment]
When you click "+" under "Link Binary With Libraries" a second time, the dialog box with the title "Choose frameworks and libraries to add" should have items under both the "Workspace" and "iOS x.y" folders. libNUSurveyor.a should be under "Workspace". If not, you may need to open the nu_surveyor project separately and build the library.

**Comment by Sophrinix** [comment]
it should, but it doesn't. In fact, there isn't even a Workspace folder.

What target am I suppose to select and what version iOS are you building this against.
What version of XCode are you using?

**Comment by Sophrinix** [comment]
Here is a better question:

When I just choose to build NUSurveyor as a target. That works.
The questions is, where is that file going?
Once I can sort that, then this build setup could be radically simplified.
Frankly, this should be two repos. one for the library and a separate one for an example project. This is kind of what git submodules are for. Anyways, thanks for the hard work on this entire system from the ruby side to this.

**Comment by yoon** [comment]
Andrew,

We've tried it both ways - two repos and one.

It turns out that it is pretty tedious the two-repo way. If you
include the library project in the example project, you can't edit the
library project in a separate XCode window. So you're constantly
closing and opening the two.

The file is going to a build folder on your machine. Mine goes to:

/Users/[myusername]/Library/Developer/Xcode/DerivedData/NUSurveyor-[super-long-alpha-string]/Build/Products/Debug-iphonesimulator/libNUSurveyor.a

You're not supposed to include it from that folder. Once it's built,
the product should be in your workspace, and should appear in the
Workspace folder.

On Mon, Jul 2, 2012 at 1:39 PM, Andrew McElroy
reply@reply.github.com
wrote:
